#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import re
import math
from decimal import Decimal, ROUND_HALF_UP

SIZE = 10
ALARM = 9

FILL_CHAR = '▪'
MID_CHAR = '▪'
EMPTY_CHAR = '▫'

FILL_COLOR = '#[fg=brightgreen]'
MID_COLOR = '#[fg=brightred]'
EMPTY_COLOR = '#[fg=default bg=default]'
ALARM_COLOR = '#[fg=brightred]'
PCT_COLOR = '#[fg=default]'

str = open('/proc/cpuinfo', 'r').read()
nproc = len(re.findall('^processor\s*:\s*\d+', str, re.MULTILINE))

str = open('/proc/loadavg', 'r').read()
load = int(str.split()[0].replace('.', '')) / nproc

pos = int(Decimal(SIZE * math.ceil(load) / 100).to_integral_value(rounding=ROUND_HALF_UP))
if pos > SIZE: pos = SIZE

fill = FILL_CHAR * (pos - 1)
empty = EMPTY_CHAR * int(SIZE - pos)
mid = "" if not pos else MID_CHAR
fill_color = ALARM_COLOR if pos >= ALARM else FILL_COLOR
mid_color = ALARM_COLOR if pos == SIZE else MID_COLOR
pct_color = ALARM_COLOR if pos >= ALARM else PCT_COLOR

print(pct_color + "{}% ".format(load) + fill_color + fill + mid_color + mid + EMPTY_COLOR + empty + '#[bg=default fg=default]')
